name: bug213123
description: sdfdsfdsf
title: fhgfhgfh
labels: bug
body:
- type: input
  attributes:
    label: Last name
- type: textarea
  attributes:
    label: "What's wrong?"
- type: markdown
  attributes:
    label: "Bugs are a bummer!"
 
