name: bug213123
description: sdfdsfdsf
title: fhgfhgfh
labels: bug
body:
- type: input
  attributes:
    label: 请填在线链接
  validations:
    required: true
- type: markdown
  attributes:
    value: "请填写问题描述或截图"
