name: bug213123
description: sdfdsfdsf
title: fhgfhgfh
labels: bug
body:
- type: input
  attributes:
    label: Last name
- type: textarea
  attributes:
    label: "What's wrong?"
    description: "How do you trigger this bug? Please walk us through it step by step."
    value: "dsf"
- type: markdown
  attributes:
    value: "Bugs are a bummer!"
 
