name: bug213123
description: sdfdsfdsf
title: fhgfhgfh
labels: bug
body:
- type: textarea
  id: describe
  attributes:
    label: "问题描述或相关截图："
    description: "详细操作步骤描述"
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: input
  id: link
  attributes:
    label: "可复现的演示链接："
    description: "重现必须是可运行的，尽量精简可复现问题的代码段，一个最小化的重现能让我们精确地定位 bug 从而快速解决问题！"
    placeholder: "请输入有效在线演示链接"
  validations:
    required: true
- type: input
  id: expectation
  attributes:
    label: "期望的结果："
- type: input
  id: os
  attributes:
    label: "操作系统："
    placeholder: "例如：window10"
  validations:
    required: true
- type: input
  id: browser
  attributes:
    label: "浏览器版本："
    placeholder: "例如：chrome 95.0.4638.69"
  validations:
    required: true
- type: input
  id: browser
  attributes:
    label: "vue 版本："
    placeholder: "例如：2.6.0"
  validations:
    required: true
- type: input
  id: browser
  attributes:
    label: "vxe-table 版本："
    placeholder: "例如：3.4.0"
  validations:
    required: true
