name: bug213123
description: sdfdsfdsf
title: fhgfhgfh
labels: bug
body:
- type: markdown
  attributes:
    value: "Bugs are a bummer!"
    description: 'sdfsdfdsf dsg'
- type: textarea
  attributes:
    label: "What's wrong?"
    description: 'For example: 10.0.1'
   validations:
     required: true
